=== what-a-fix/pure-php-test-skills/theme_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="theme" type="themeType">
        <xs:annotation>
            <xs:documentation>Root Element</xs:documentation>
        </xs:annotation>
    </xs:element>

    <xs:complexType name="themeType">
        <xs:all>
            <xs:element ref="lang"/>
            <xs:element ref="tag"/>
            <xs:element ref="words"/>
        </xs:all>
    </xs:complexType>

    <xs:element name="lang" type="xs:language" nillable="false">
        <xs:annotation>
            <xs:documentation>the language for this theme</xs:documentation>
        </xs:annotation>
    </xs:element>

    <xs:element name="tag" type="xs:string" abstract="false">
        <xs:annotation>
            <xs:documentation>the tag for this theme</xs:documentation>
        </xs:annotation>
    </xs:element>

    <xs:element name="words" type="wordsType">
        <xs:annotation>
            <xs:documentation>words type</xs:documentation>
        </xs:annotation>
    </xs:element>

    <xs:complexType name="wordsType">
        <xs:annotation>
            <xs:documentation>words type definition</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element ref="word" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="word" type="wordType">
        <xs:annotation>
            <xs:documentation>word type</xs:documentation>
        </xs:annotation>
    </xs:element>

    <xs:complexType name="wordType">
        <xs:annotation>
            <xs:documentation>word type definition</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="value" maxOccurs="unbounded">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[^\s]+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="weight" default="1" type="weightType"/>
    </xs:complexType>

    <xs:simpleType name="weightType">
        <xs:annotation>
            <xs:documentation>weight type</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:decimal">
            <xs:pattern value="0(\.[0-9]+)?|1"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== what-a-fix/pure-php-test-skills/tests/assets/train.xml
<?xml version="1.0" encoding="utf-8"?>
<theme
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../theme_schema.xsd"
>
    <lang>fr</lang>
    <tag>train</tag>
    <words>
        <word>
            <value>rail</value>
        </word>
        <word>
            <value>locomotive</value>
        </word>
    </words>
</theme>

=== what-a-fix/pure-php-test-skills/tests/assets/basic_theme.xml
<?xml version="1.0" encoding="utf-8"?>
<theme
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../theme_schema.xsd"
>
    <lang>fr</lang>
    <tag>test</tag>
    <words>
        <word>
            <value>phpunit</value>
        </word>
        <word>
            <value>test</value>
            <value>testing</value>
        </word>
        <word weight="0.5">
            <value>error</value>
        </word>
    </words>
</theme>

=== what-a-fix/pure-php-test-skills/tests/assets/bathroom.xml
<?xml version="1.0" encoding="utf-8"?>
<theme
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../theme_schema.xsd"
>
    <lang>fr</lang>
    <tag>bathroom</tag>
    <words>
        <word weight="0.75">
            <value>lavabo</value>
        </word>
        <word>
            <value>baignoire</value>
        </word>
        <word>
            <value>douche</value>
        </word>
        <word weight="0.25">
            <value>toilette</value>
        </word>
        <word weight="0.5">
            <value>savon</value>
        </word>
        <word weight="0.5">
            <value>shampoing</value>
        </word>
        <word weight="0.05">
            <value>pharmacie</value>
        </word>
        <word>
            <value>porte-serviette</value>
        </word>
        <word>
            <value>bain</value>
        </word>
    </words>
</theme>

=== what-a-fix/pure-php-test-skills/tests/assets/school.xml
<?xml version="1.0" encoding="utf-8"?>
<theme
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../theme_schema.xsd"
>
    <lang>fr</lang>
    <tag>school</tag>
    <words>
        <word weight="0.75">
            <value>école</value>
        </word>
        <word>
            <value>faute</value>
        </word>
        <word>
            <value>grammaire</value>
        </word>
        <word weight="0.25">
            <value>éducation</value>
        </word>
        <word weight="0.5">
            <value>punition</value>
        </word>
        <word weight="0.5">
            <value>bulletin</value>
        </word>
        <word weight="0.05">
            <value>institutrice</value>
        </word>
        <word>
            <value>étude</value>
        </word>
        <word>
            <value>problème</value>
        </word>
        <word>
            <value>cours</value>
        </word>
        <word>
            <value>classe</value>
        </word>
        <word>
            <value>devoir</value>
        </word>
        <word>
            <value>élève</value>
        </word>
        <word>
            <value>instituteur</value>
        </word>
        <word>
            <value>leçon</value>
        </word>
        <word>
            <value>savoir</value>
        </word>
        <word>
            <value>science</value>
        </word>
        <word>
            <value>apprentissage</value>
        </word>
        <word>
            <value>mot</value>
        </word>
        <word>
            <value>écolier</value>
        </word>
        <word>
            <value>parole</value>
        </word>
        <word>
            <value>récréation</value>
        </word>
        <word>
            <value>rentrée</value>
        </word>
        <word>
            <value>vacance</value>
        </word>
        <word>
            <value>exemple</value>
        </word>
        <word>
            <value>instruction</value>
        </word>
        <word>
            <value>livre</value>
        </word>
        <word>
            <value>page</value>
        </word>
        <word>
            <value>problème</value>
        </word>
        <word>
            <value>stylo</value>
        </word>
        <word>
            <value>math</value>
        </word>
        <word>
            <value>physique</value>
        </word>
        <word>
            <value>chimie</value>
        </word>
        <word>
            <value>collège</value>
        </word>
        <word>
            <value>lycée</value>
        </word>
        <word>
            <value>formation</value>
        </word>
        <word>
            <value>scolaire</value>
        </word>
        <word>
            <value>enseignement</value>
        </word>
        <word>
            <value>correction</value>
        </word>
        <word>
            <value>poésie</value>
        </word>
        <word>
            <value>poème</value>
        </word>
        <word>
            <value>dictionnaire</value>
        </word>
        <word>
            <value>rédaction</value>
        </word>
        <word>
            <value>note</value>
        </word>
        <word>
            <value>question</value>
        </word>
        <word>
            <value>examen</value>

        </word>
        <word>
            <value>oral</value>
        </word>
        <word>
            <value>travail</value>
        </word>
    </words>
</theme>

=== what-a-fix/pure-php-test-skills/tests/assets/walk.xml
<?xml version="1.0" encoding="utf-8"?>
<theme
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../theme_schema.xsd"
>
    <lang>fr</lang>
    <tag>walk</tag>
    <words>
        <word>
            <value>ballade</value>
        </word>
        <word>
            <value>sortie</value>
        </word>
        <word>
            <value>promener</value>
        </word>
        <word>
            <value>promenade</value>
        </word>
        <word>
            <value>parc</value>
        </word>
    </words>
</theme>
